#!/usr/bin/python3
"""
file: make_workspace.py
coding: utf-8
author: holger
version: 3.0
license: AGPL-3.0
belongs: WebBot-External
"""
import os
import shutil
import sys

usage_str = '''USAGE: 
make_workspace.py path mode=(classic | auto | empty | once)
    - mode default type: classic
    - e.g.  make_workspace.py Workspaces/Demo1 mode=auto
    - e.g.  make_workspace.py Workspaces/Demo2
'''

if not (len(sys.argv) == 2 or len(sys.argv) == 3):
    print('Error Usage')
    print(usage_str)
    exit(1)

cfg_data = os.path.join(os.path.split(__file__)[0], 'data')
assert os.path.isdir(cfg_data), 'miss data files.'
workspace = sys.argv[1]
workspace_data = os.path.join(sys.argv[1], 'data')
mode = sys.argv[2] if len(sys.argv) == 3 else 'mode=classic'
if not mode.startswith('mode='):
    print('Error Usage')
    print(usage_str)
    exit(2)
mode = mode[5:]
if mode not in ('classic', 'auto', 'empty', 'once'):
    print('Error Usage')
    print(usage_str)
    exit(3)

if not os.path.isdir(workspace_data):
    os.makedirs(workspace_data)
for file in os.listdir(cfg_data):
    shutil.copy(os.path.join(cfg_data, file), workspace_data)
with open(os.path.join(workspace, 'main.py'), 'w', encoding='utf-8') as src:
    src.write('# This is generated by program.\n')
    if mode == 'empty':
        src.write('import bot\n')
    elif mode == 'classic':
        src.write('''
import bot


# your own job
# map_name is the name property of Mapping Element in map.xml
# user_id is the id property of User Element in configuration.xml
# define another function that runs before bot started if you want, 
# and pass it as a parameter named 'before' into the decorator 'bot.job_maker'
@bot.job_maker(map_name='Type Mapping name here', user_id='Type User id here, or `None` for all user')
def my_job():
    # do something after bot run
    pass


if __name__ == "__main__":
    bot.run(my_job)
''')
    elif mode == 'auto':
        src.write('''
# use default run mode: 
# use the first Mapping Element in map.xml, use all the User Element defined in configuration.xml

import bot


if __name__ == "__main__":
    bot.default.default_run()
''')
    elif mode == 'once':
        src.write('''
# bot only runs when script was running

import bot


# map_name is the name property of Mapping Element in map.xml
# user_id is the id property of User Element in configuration.xml
bot.run_once(map_name='Type Mapping name here', user_id='Type User id here, or `None` for all user')
''')

print('workspace generate finished.')
