# This is generated by program.
import sys
import webbrowser

import requests

import bot
from bot import resources

dkjl_website = 'http://dk.suda.edu.cn/default/work/suda/jkxxtb/dkjl.jsp'
map_url = 'https://api.holgerbest.top/DailyReport/v3/map.xml'


def update():
    with open(resources.MAP_FILE, 'w', encoding='utf-8') as update_map_file:
        update_map_file.write(requests.get(map_url).text)


# your own job
@bot.job_maker(map_name='report', user_id=None, before=update)
def my_job():
    # do something after bot run
    webbrowser.open(dkjl_website)


if __name__ == "__main__":
    if '--once' in sys.argv:
        bot.run_once(map_name='report', user_id=None)
        webbrowser.open(dkjl_website)
    else:
        bot.run(my_job)
